name: ReleaseBuild
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Install dependencies
      run: dotnet restore src\SharpWebview\SharpWebview.csproj
    - name: Build
      run: dotnet build src\SharpWebview\SharpWebview.csproj --configuration Release
    - name: Package nuget
      run: dotnet pack src\SharpWebview\SharpWebview.csproj --configuration Release
    - name: Prep packages
      run: dotnet nuget add source --username ${{ secrets.NUGET_PACKAGE_OWNER }} --password ${{ secrets.NUGET_PACKAGE_TOKEN }} --name github "https://nuget.pkg.github.com/icavalheiro/index.json"
    - name: Push package to GitHub packages 
      run: dotnet nuget push src\SharpWebview\bin\Release\*.nupkg --api-key ${{ secrets.NUGET_PACKAGE_TOKEN }} --source "github"